	QsysCore u0 (
		.clk_clk                                                                                         (<connected-to-clk_clk>),                                                                                         //                                             clk.clk
		.pio_0_external_connection_export                                                                (<connected-to-pio_0_external_connection_export>),                                                                //                       pio_0_external_connection.export
		.pio_1_external_connection_export                                                                (<connected-to-pio_1_external_connection_export>),                                                                //                       pio_1_external_connection.export
		.pio_2_external_connection_export                                                                (<connected-to-pio_2_external_connection_export>),                                                                //                       pio_2_external_connection.export
		.reset_reset_n                                                                                   (<connected-to-reset_reset_n>),                                                                                   //                                           reset.reset_n
		.spi_slave_to_avalon_mm_master_bridge_0_export_0_mosi_to_the_spislave_inst_for_spichain          (<connected-to-spi_slave_to_avalon_mm_master_bridge_0_export_0_mosi_to_the_spislave_inst_for_spichain>),          // spi_slave_to_avalon_mm_master_bridge_0_export_0.mosi_to_the_spislave_inst_for_spichain
		.spi_slave_to_avalon_mm_master_bridge_0_export_0_nss_to_the_spislave_inst_for_spichain           (<connected-to-spi_slave_to_avalon_mm_master_bridge_0_export_0_nss_to_the_spislave_inst_for_spichain>),           //                                                .nss_to_the_spislave_inst_for_spichain
		.spi_slave_to_avalon_mm_master_bridge_0_export_0_miso_to_and_from_the_spislave_inst_for_spichain (<connected-to-spi_slave_to_avalon_mm_master_bridge_0_export_0_miso_to_and_from_the_spislave_inst_for_spichain>), //                                                .miso_to_and_from_the_spislave_inst_for_spichain
		.spi_slave_to_avalon_mm_master_bridge_0_export_0_sclk_to_the_spislave_inst_for_spichain          (<connected-to-spi_slave_to_avalon_mm_master_bridge_0_export_0_sclk_to_the_spislave_inst_for_spichain>),          //                                                .sclk_to_the_spislave_inst_for_spichain
		.pio_3_external_connection_export                                                                (<connected-to-pio_3_external_connection_export>),                                                                //                       pio_3_external_connection.export
		.pio_4_external_connection_export                                                                (<connected-to-pio_4_external_connection_export>)                                                                 //                       pio_4_external_connection.export
	);

